class RegisterationType
  @@REGISTRATION_OPEN = 1
  @@REGISTRATION_WITH_INVITATION = 2
  @@REGISTRATION_CLOSE = 3
  
  def self.REGISTRATION_OPEN
    @@REGISTRATION_OPEN
  end
  def self.REGISTRATION_WITH_INVITATION
    @@REGISTRATION_WITH_INVITATION
  end
  def self.REGISTRATION_CLOSE
    @@REGISTRATION_CLOSE
  end
end